allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@remotion/bundler@4.0.534'
  - '@remotion/captions@4.0.534'
  - '@remotion/cli@4.0.534'
  - '@remotion/codemods@4.0.534'
  - '@remotion/compositor-darwin-arm64@4.0.534'
  - '@remotion/compositor-darwin-x64@4.0.534'
  - '@remotion/compositor-linux-arm64-gnu@4.0.534'
  - '@remotion/compositor-linux-arm64-musl@4.0.534'
  - '@remotion/compositor-linux-x64-gnu@4.0.534'
  - '@remotion/compositor-linux-x64-musl@4.0.534'
  - '@remotion/compositor-win32-x64-msvc@4.0.534'
  - '@remotion/elevenlabs@4.0.534'
  - '@remotion/google-fonts@4.0.534'
  - '@remotion/licensing@4.0.534'
  - '@remotion/media-parser@4.0.534'
  - '@remotion/media-utils@4.0.534'
  - '@remotion/media@4.0.534'
  - '@remotion/openai-whisper@4.0.534'
  - '@remotion/paths@4.0.534'
  - '@remotion/player@4.0.534'
  - '@remotion/renderer@4.0.534'
  - '@remotion/sdk@4.0.534'
  - '@remotion/shapes@4.0.534'
  - '@remotion/streaming@4.0.534'
  - '@remotion/studio-protocol@4.0.534'
  - '@remotion/studio-server@4.0.534'
  - '@remotion/studio-shared@4.0.534'
  - '@remotion/studio@4.0.534'
  - '@remotion/tailwind-v4@4.0.534'
  - '@remotion/timeline-utils@4.0.534'
  - '@remotion/transitions@4.0.534'
  - '@remotion/web-renderer@4.0.534'
  - '@remotion/zod-types@4.0.534'
  - remotion@4.0.534
