/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowRouteImport } from './routes/how'
import { Route as KeyRouteImport } from './routes/key'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as RaidsRouteImport } from './routes/raids'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RaidRaidIdRouteImport } from './routes/raid.$raidId'
import { Route as RRaidIdSeatRouteImport } from './routes/r.$raidId.$seat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyRoute = KeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const RaidsRoute = RaidsRouteImport.update({
  id: '/raids',
  path: '/raids',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RaidRaidIdRoute = RaidRaidIdRouteImport.update({
  id: '/raid/$raidId',
  path: '/raid/$raidId',
  getParentRoute: () => rootRouteImport,
} as any)
const RRaidIdSeatRoute = RRaidIdSeatRouteImport.update({
  id: '/r/$raidId/$seat',
  path: '/r/$raidId/$seat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/key': typeof KeyRoute
  '/practice': typeof PracticeRoute
  '/raids': typeof RaidsRoute
  '/terms': typeof TermsRoute
  '/raid/$raidId': typeof RaidRaidIdRoute
  '/r/$raidId/$seat': typeof RRaidIdSeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/key': typeof KeyRoute
  '/practice': typeof PracticeRoute
  '/raids': typeof RaidsRoute
  '/terms': typeof TermsRoute
  '/raid/$raidId': typeof RaidRaidIdRoute
  '/r/$raidId/$seat': typeof RRaidIdSeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/key': typeof KeyRoute
  '/practice': typeof PracticeRoute
  '/raids': typeof RaidsRoute
  '/terms': typeof TermsRoute
  '/raid/$raidId': typeof RaidRaidIdRoute
  '/r/$raidId/$seat': typeof RRaidIdSeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how'
    | '/key'
    | '/practice'
    | '/raids'
    | '/terms'
    | '/raid/$raidId'
    | '/r/$raidId/$seat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how'
    | '/key'
    | '/practice'
    | '/raids'
    | '/terms'
    | '/raid/$raidId'
    | '/r/$raidId/$seat'
  id:
    | '__root__'
    | '/'
    | '/how'
    | '/key'
    | '/practice'
    | '/raids'
    | '/terms'
    | '/raid/$raidId'
    | '/r/$raidId/$seat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowRoute: typeof HowRoute
  KeyRoute: typeof KeyRoute
  PracticeRoute: typeof PracticeRoute
  RaidsRoute: typeof RaidsRoute
  TermsRoute: typeof TermsRoute
  RaidRaidIdRoute: typeof RaidRaidIdRoute
  RRaidIdSeatRoute: typeof RRaidIdSeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key': {
      id: '/key'
      path: '/key'
      fullPath: '/key'
      preLoaderRoute: typeof KeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raids': {
      id: '/raids'
      path: '/raids'
      fullPath: '/raids'
      preLoaderRoute: typeof RaidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raid/$raidId': {
      id: '/raid/$raidId'
      path: '/raid/$raidId'
      fullPath: '/raid/$raidId'
      preLoaderRoute: typeof RaidRaidIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$raidId/$seat': {
      id: '/r/$raidId/$seat'
      path: '/r/$raidId/$seat'
      fullPath: '/r/$raidId/$seat'
      preLoaderRoute: typeof RRaidIdSeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowRoute: HowRoute,
  KeyRoute: KeyRoute,
  PracticeRoute: PracticeRoute,
  RaidsRoute: RaidsRoute,
  TermsRoute: TermsRoute,
  RaidRaidIdRoute: RaidRaidIdRoute,
  RRaidIdSeatRoute: RRaidIdSeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
