/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowRouteImport } from './routes/how'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RaidRaidIdRouteImport } from './routes/raid.$raidId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RaidRaidIdRoute = RaidRaidIdRouteImport.update({
  id: '/raid/$raidId',
  path: '/raid/$raidId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/practice': typeof PracticeRoute
  '/terms': typeof TermsRoute
  '/raid/$raidId': typeof RaidRaidIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/practice': typeof PracticeRoute
  '/terms': typeof TermsRoute
  '/raid/$raidId': typeof RaidRaidIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/practice': typeof PracticeRoute
  '/terms': typeof TermsRoute
  '/raid/$raidId': typeof RaidRaidIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/how' | '/practice' | '/terms' | '/raid/$raidId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/how' | '/practice' | '/terms' | '/raid/$raidId'
  id: '__root__' | '/' | '/how' | '/practice' | '/terms' | '/raid/$raidId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowRoute: typeof HowRoute
  PracticeRoute: typeof PracticeRoute
  TermsRoute: typeof TermsRoute
  RaidRaidIdRoute: typeof RaidRaidIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raid/$raidId': {
      id: '/raid/$raidId'
      path: '/raid/$raidId'
      fullPath: '/raid/$raidId'
      preLoaderRoute: typeof RaidRaidIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowRoute: HowRoute,
  PracticeRoute: PracticeRoute,
  TermsRoute: TermsRoute,
  RaidRaidIdRoute: RaidRaidIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
